# Generated by Django 6.0.4 on 2026-05-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25)),
                ('student_id', models.IntegerField(max_length=10)),
                ('student_dept', models.CharField(max_length=15)),
            ],
        ),
    ]
